#!/bin/bash
#

## Insure execution occur within base directory of this script
#
SCRIPT_PATH=$(dirname $(readlink -f $0))
DOCKER_NAME=$(basename $SCRIPT_PATH)
cd $SCRIPT_PATH

DOCKER_HOST_IP=$(ifconfig eth0 | awk -F ' *|:' '/inet addr/{print $4}')

docker stop $DOCKER_NAME 2>/dev/null
docker rm -f $DOCKER_NAME 2>/dev/null
docker run -it --rm --name $DOCKER_NAME -P -e SERVICE_TAGS=production -e DOCKER_HOST_IP=$DOCKER_HOST_IP $DOCKER_NAME bash
